spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-cloud-zuul
# 服务端口号
server:
  port: 9099
#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/
zuul:
  routes:
    api-a:
      path: /eureka-client1/**
      service-id: http://localhost:52601/
      sensitive-headers:
    api-b:
      path: /eureka-client2/**
      service-id: EUREKA-CLIENT2
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      client-id: client_test
      client-secret: secret_test
    resource:
      user-info-uri: http://localhost:8080/api/v1/users/principal
      prefer-token-info: false